In [1]:
import pandas as pd
import tweepy
import json

In [2]:
consumer_key='xxxxx'
consumer_secret='xxxxx'
access_token='xxxxx-xxxxx'
access_token_secret='xxxxx'

auth=tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_token,access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True,wait_on_rate_limit_notify=True)

In [3]:
hashtag_yang_dicari='#wfh'
crawl_tweet=api.search(q=hashtag_yang_dicari,count=100,include_entities=False)

In [4]:
json_data=[r._json for r in crawl_tweet]
df= pd.json_normalize(json_data)

In [5]:
df.head()

,created_at,id,id_str,text,truncated,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,retweeted_status.quoted_status.coordinates,retweeted_status.quoted_status.place,retweeted_status.quoted_status.contributors,retweeted_status.quoted_status.is_quote_status,retweeted_status.quoted_status.retweet_count,retweeted_status.quoted_status.favorite_count,retweeted_status.quoted_status.favorited,retweeted_status.quoted_status.retweeted,retweeted_status.quoted_status.possibly_sensitive,retweeted_status.quoted_status.lang
0,Sun Dec 06 22:36:30 +0000 2020,1335714763679158274,1335714763679158274,Stephan Howeg from the Adecco Group shares how...,True,"<a href=""https://app.clearviewsocial.com"" rel=...",NaN,None,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sun Dec 06 22:30:49 +0000 2020,1335713330942648320,1335713330942648320,@miles_k A whole bunch of computer accessories...,False,"<a href=""http://twitter.com/download/android"" ...",1.335706e+18,1335706384382521344,17839976.0,17839976,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sun Dec 06 22:26:47 +0000 2020,1335712317095309313,1335712317095309313,Heading to Barangka river bunguio ZC..\n\n#alt...,False,"<a href=""http://twitter.com/download/android"" ...",NaN,None,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sun Dec 06 22:26:00 +0000 2020,1335712121972256770,1335712121972256770,"If your firm's working from home, it's essenti...",True,"<a href=""https://buffer.com"" rel=""nofollow"">Bu...",NaN,None,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sun Dec 06 22:25:04 +0000 2020,1335711884239056899,1335711884239056899,I finally have a designated work space! #WFH h...,False,"<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#menyimpan menjadi csv
df.to_csv("data_tweet.csv",index=False)